### ISSUE TITLE
Things crash :)

### ISSUE THREAD

**Issue by sils** [lordmauve/murder#1]
Trying out pushing a few keys on the hallway after the few intro texts gives:

```
lasse@lsmob ~/prog/tmp/murder (git)-[master] % python run_game.py
murder.py:783: DeprecationWarning: invalid escape sequence \/
  '\/',
Traceback (most recent call last):
  File "/home/lasse/venvs/def/bin/pgzrun", line 11, in <module>
    sys.exit(main())
  File "/home/lasse/venvs/def/lib/python3.6/site-packages/pgzero/runner.py", line 89, in main
    PGZeroGame(mod).run()
  File "/home/lasse/venvs/def/lib/python3.6/site-packages/pgzero/game.py", line 215, in run
    update(dt)
  File "/home/lasse/venvs/def/lib/python3.6/site-packages/pgzero/game.py", line 166, in <lambda>
    return lambda dt: update()
  File "murder.py", line 573, in update
    move_billy()
  File "murder.py", line 593, in move_billy
    play_billy_anim(billy_walk_r)
  File "murder.py", line 631, in play_billy_anim
    next_frame()
  File "murder.py", line 645, in next_frame
    billy.image = next(billy.frames)
  File "/home/lasse/venvs/def/lib/python3.6/site-packages/pgzero/actor.py", line 152, in image
    self._surf = loaders.images.load(image)
  File "/home/lasse/venvs/def/lib/python3.6/site-packages/pgzero/loaders.py", line 118, in load
    p = os.path.join(self._root(), name)
  File "/home/lasse/venvs/def/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/lasse/venvs/def/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'Surface'
python run_game.py  18.38s user 6.74s system 101% cpu 24.653 total
```

**Comment by lordmauve** [comment]
I think this game needs the head version of Pygame Zero.

**Comment by sils** [comment]
I was about to comment since I found https://github.com/lordmauve/murder/issues/3 :)
